/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_lightsout_graphique_brunet_mares;

/**
 *
 * @author egnma
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        panneauChronometre.setVisible(false);
        PanneauInfosJoueur.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grille = new javax.swing.JPanel();
        panneauChronometre = new javax.swing.JPanel();
        PanneauInfosJoueur = new javax.swing.JPanel();
        NbCoupsJoues = new javax.swing.JLabel();
        InfosDuJoueur = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        NbCasesRestantes = new javax.swing.JLabel();
        panneauInitialisationPartie = new javax.swing.JPanel();
        nom_Joueur = new javax.swing.JLabel();
        NomJoueur = new javax.swing.JTextField();
        debuterPartie = new javax.swing.JButton();
        numero_CarteBancaire = new javax.swing.JLabel();
        numeroJoueur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Grille.setBackground(new java.awt.Color(204, 255, 255));
        Grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(Grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 800, 800));

        panneauChronometre.setBackground(new java.awt.Color(204, 204, 204));
        panneauChronometre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panneauChronometre, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 420, 270));

        PanneauInfosJoueur.setBackground(new java.awt.Color(153, 153, 0));
        PanneauInfosJoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NbCoupsJoues.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        NbCoupsJoues.setText("Nombre de coups joués:");
        PanneauInfosJoueur.add(NbCoupsJoues, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        InfosDuJoueur.setBackground(new java.awt.Color(204, 204, 204));
        InfosDuJoueur.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        InfosDuJoueur.setText("INFOS DU JOUEUR:");
        PanneauInfosJoueur.add(InfosDuJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, 30));

        Nom.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        Nom.setText("Nom :");
        PanneauInfosJoueur.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, 30));

        NbCasesRestantes.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        NbCasesRestantes.setText("Nombre cases restantes :");
        PanneauInfosJoueur.add(NbCasesRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 30));

        getContentPane().add(PanneauInfosJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 420, 220));

        panneauInitialisationPartie.setBackground(new java.awt.Color(204, 204, 255));
        panneauInitialisationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom_Joueur.setText("NUMERO DE CARTE BANCAIRE :");
        panneauInitialisationPartie.add(nom_Joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        NomJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomJoueurActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(NomJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, 30));

        debuterPartie.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        debuterPartie.setText("Débuter Partie !");
        debuterPartie.setActionCommand("Débuter partie");
        debuterPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debuterPartieActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(debuterPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 40));

        numero_CarteBancaire.setText("NOM DU JOUEUR :");
        panneauInitialisationPartie.add(numero_CarteBancaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        numeroJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroJoueurActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(numeroJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 170, 30));

        getContentPane().add(panneauInitialisationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, 420, 140));

        setBounds(0, 0, 1436, 910);
    }// </editor-fold>//GEN-END:initComponents

    private void NomJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomJoueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomJoueurActionPerformed

    private void numeroJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroJoueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroJoueurActionPerformed

    private void debuterPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debuterPartieActionPerformed
        panneauChronometre.setVisible(true);
        PanneauInfosJoueur.setVisible(true);
    }//GEN-LAST:event_debuterPartieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Grille;
    private javax.swing.JLabel InfosDuJoueur;
    private javax.swing.JLabel NbCasesRestantes;
    private javax.swing.JLabel NbCoupsJoues;
    private javax.swing.JLabel Nom;
    private javax.swing.JTextField NomJoueur;
    private javax.swing.JPanel PanneauInfosJoueur;
    private javax.swing.JButton debuterPartie;
    private javax.swing.JLabel nom_Joueur;
    private javax.swing.JTextField numeroJoueur;
    private javax.swing.JLabel numero_CarteBancaire;
    private javax.swing.JPanel panneauChronometre;
    private javax.swing.JPanel panneauInitialisationPartie;
    // End of variables declaration//GEN-END:variables
}
