/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package miniprojet_lightsout_graphique_brunet_mares;

import java.awt.event.ActionEvent;
import java.util.Random;

/**
 *
 * @author egnma
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form FenetreDeJeu
     */
    Grille grilleJeu = new Grille();
    Joueur joueurCourant;
    
    public FenetreDeJeu() {
        initComponents();
        panneauChronometre.setVisible(false);
        PanneauInfosJoueur.setVisible(false);
  
        for(int i=4; i>=0 ; i--){
            for(int j=0; j<5 ; j++){
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.tableauDeJeu[i][j]);

                panneau_grille.add(cellGraph);
                
            }
        }
   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        panneauChronometre = new javax.swing.JPanel();
        PanneauInfosJoueur = new javax.swing.JPanel();
        NbCoupsJoues = new javax.swing.JLabel();
        InfosDuJoueur = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        NbCasesRestantes = new javax.swing.JLabel();
        nom_label = new javax.swing.JLabel();
        CB_infos = new javax.swing.JLabel();
        CB_label = new javax.swing.JLabel();
        NbCases_label = new javax.swing.JLabel();
        NbCoupsJoues_label = new javax.swing.JLabel();
        panneauInitialisationPartie = new javax.swing.JPanel();
        nom_Joueur = new javax.swing.JLabel();
        NomJoueur = new javax.swing.JTextField();
        debuterPartie = new javax.swing.JButton();
        numero_CarteBancaire = new javax.swing.JLabel();
        numeroJoueur = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(255, 102, 102));
        panneau_grille.setLayout(new java.awt.GridLayout(5, 5));
        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 800, 800));

        panneauChronometre.setBackground(new java.awt.Color(153, 153, 153));
        panneauChronometre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panneauChronometre, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 530, 420, 270));

        PanneauInfosJoueur.setBackground(new java.awt.Color(204, 204, 204));
        PanneauInfosJoueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NbCoupsJoues.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        NbCoupsJoues.setText("Nombre de coups joués:");
        PanneauInfosJoueur.add(NbCoupsJoues, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 30));

        InfosDuJoueur.setBackground(new java.awt.Color(204, 204, 204));
        InfosDuJoueur.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        InfosDuJoueur.setText("INFOS DU JOUEUR:");
        PanneauInfosJoueur.add(InfosDuJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 310, 30));

        Nom.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        Nom.setText("Nom :");
        PanneauInfosJoueur.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 40, 30));

        NbCasesRestantes.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        NbCasesRestantes.setText("Nombre cases restantes :");
        PanneauInfosJoueur.add(NbCasesRestantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 160, 30));

        nom_label.setText("Nom joueur ");
        PanneauInfosJoueur.add(nom_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 180, 20));

        CB_infos.setFont(new java.awt.Font("Calibri Light", 0, 16)); // NOI18N
        CB_infos.setText("Nom :");
        PanneauInfosJoueur.add(CB_infos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, 30));

        CB_label.setText("Infos bancaires");
        PanneauInfosJoueur.add(CB_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 84, 210, 20));

        NbCases_label.setText("jLabel1");
        PanneauInfosJoueur.add(NbCases_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 114, 150, 30));

        NbCoupsJoues_label.setText("jLabel1");
        PanneauInfosJoueur.add(NbCoupsJoues_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 140, 30));

        getContentPane().add(PanneauInfosJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 290, 420, 220));

        panneauInitialisationPartie.setBackground(new java.awt.Color(204, 204, 204));
        panneauInitialisationPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nom_Joueur.setText("NUMERO DE CARTE BANCAIRE :");
        panneauInitialisationPartie.add(nom_Joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, 30));

        NomJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomJoueurActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(NomJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, 30));

        debuterPartie.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        debuterPartie.setText("Débuter Partie !");
        debuterPartie.setActionCommand("Débuter partie");
        debuterPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debuterPartieActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(debuterPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, 40));

        numero_CarteBancaire.setText("NOM DU JOUEUR :");
        panneauInitialisationPartie.add(numero_CarteBancaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        numeroJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroJoueurActionPerformed(evt);
            }
        });
        panneauInitialisationPartie.add(numeroJoueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 170, 30));

        getContentPane().add(panneauInitialisationPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, 420, 140));

        setBounds(0, 0, 1436, 910);
    }// </editor-fold>//GEN-END:initComponents

    private void NomJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomJoueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomJoueurActionPerformed

    private void numeroJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroJoueurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroJoueurActionPerformed

    private void debuterPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debuterPartieActionPerformed
        panneauChronometre.setVisible(true);
        PanneauInfosJoueur.setVisible(true);
        initialiserPartie();
        panneau_grille.repaint();
        debuterPartie.setEnabled(false);
    }//GEN-LAST:event_debuterPartieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }
    
        public void initialiserPartie(){
            int nombreCoupsJoues = 0 ;
            Random rand = new Random();
            String nomJoueur1 = numeroJoueur.getText();
            nom_label.setText(nomJoueur1);
            CB_label.setText("Transaction 100$ validée");
            NbCases_label.setText(nombreCoupsJoues+"");
            for (int i = 0 ; i < 25 ; i++){
            
                Light lumiere = new Light();
            
        }
    
        
            for (int i = 0 ; i < 7 ; i++){
            
                int ligneStart = rand.nextInt(5);
                int colonneStart = rand.nextInt(5);
            
                grilleJeu.switchOnOff(ligneStart,colonneStart);
            
        }
        }
        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CB_infos;
    private javax.swing.JLabel CB_label;
    private javax.swing.JLabel InfosDuJoueur;
    private javax.swing.JLabel NbCasesRestantes;
    private javax.swing.JLabel NbCases_label;
    private javax.swing.JLabel NbCoupsJoues;
    private javax.swing.JLabel NbCoupsJoues_label;
    private javax.swing.JLabel Nom;
    private javax.swing.JTextField NomJoueur;
    private javax.swing.JPanel PanneauInfosJoueur;
    private javax.swing.JButton debuterPartie;
    private javax.swing.JLabel nom_Joueur;
    private javax.swing.JLabel nom_label;
    private javax.swing.JTextField numeroJoueur;
    private javax.swing.JLabel numero_CarteBancaire;
    private javax.swing.JPanel panneauChronometre;
    private javax.swing.JPanel panneauInitialisationPartie;
    private javax.swing.JPanel panneau_grille;
    // End of variables declaration//GEN-END:variables
}
